version: '3'

services:
  machine-manager:
    container_name: machine-manager
    image: ghcr.io/mpiekutowski/machine_manager
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - linter_network
    environment:
      - SECRET_KEY=123

  load-balancer:
    container_name: load-balancer
    image: ghcr.io/mpiekutowski/load_balancer
    ports:
      - "8080:8080"   
    networks:
      - linter_network
    environment:
      - SECRET_KEY=123

networks:
  linter_network:
    name: linter_network
    driver: bridge